import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,Briefcase,UserRound,Bookmark,Home,Settings,ExternalLink,MapPin,RefreshCw,CheckCircle2,Wifi,WifiOff,ChevronRight,Target, Bell} from 'lucide-react';
import './styles.css';
if ('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));

type Job={id:string;title:string;company:string;location:string;remote:boolean;canonical_url:string;source:string;salary?:string;skills?:string[]};
type AppRow={id:string;job_id:string;status:string;notes?:string};
const API=(import.meta.env.VITE_API_URL||'http://localhost:8000').replace(/\/$/,'');
async function req(path:string,init?:RequestInit){const r=await fetch(API+path,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.json()}
function App(){
 const [tab,setTab]=useState('home'),[jobs,setJobs]=useState<Job[]>([]),[apps,setApps]=useState<AppRow[]>([]),[loading,setLoading]=useState(false),[online,setOnline]=useState(true);
 const [email,setEmail]=useState(localStorage.getItem('cos_email')||'demo@careeros.app'),[uid,setUid]=useState(localStorage.getItem('cos_uid')||'');
 const [skills,setSkills]=useState(localStorage.getItem('cos_skills')||'Active Directory, Windows Server, GPO'),[locations,setLocations]=useState(localStorage.getItem('cos_locations')||'Lucknow, Noida'),[remote,setRemote]=useState(localStorage.getItem('cos_remote')==='true');
 const [q,setQ]=useState(''),[loc,setLoc]=useState('');
 async function ensureUser(){if(uid)return uid; const u=await req('/v1/users',{method:'POST',body:JSON.stringify({email})});setUid(u.id);localStorage.setItem('cos_uid',u.id);return u.id}
 async function load(){setLoading(true);try{const id=await ensureUser();const [j,a]=await Promise.all([req('/v1/jobs?limit=50'),req('/v1/applications/'+id)]);setJobs(j);setApps(a);setOnline(true)}catch{setOnline(false)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function search(){setLoading(true);try{let p='/v1/jobs?limit=50';if(q)p+='&q='+encodeURIComponent(q);if(loc)p+='&location='+encodeURIComponent(loc);setJobs(await req(p));setOnline(true)}catch{setOnline(false)}finally{setLoading(false)}}
 async function track(j:Job){const id=await ensureUser();try{await req('/v1/applications',{method:'POST',body:JSON.stringify({user_id:id,job_id:j.id})});setApps(await req('/v1/applications/'+id))}catch{setOnline(false)}}
 async function save(){try{localStorage.setItem('cos_email',email);localStorage.setItem('cos_skills',skills);localStorage.setItem('cos_locations',locations);localStorage.setItem('cos_remote',String(remote));const id=await ensureUser();await req('/v1/users/'+id+'/profile',{method:'PUT',body:JSON.stringify({skills:skills.split(',').map(x=>x.trim()).filter(Boolean),locations:locations.split(',').map(x=>x.trim()).filter(Boolean),remote_preferred:remote})});setOnline(true)}catch{setOnline(false)}}
 const featured=useMemo(()=>jobs.slice(0,6),[jobs]);
 return <div className="app"><header><div className="brand"><div className="logo">C</div><div><b>CareerOS</b><small>Connected career workspace</small></div></div><div className={'status '+(online?'on':'off')}>{online?<Wifi size={14}/>:<WifiOff size={14}/>} {online?'Connected':'Offline'}</div></header>
 <main>{tab==='home'&&<><section className="hero"><span className="eyebrow">YOUR CAREER, CONNECTED</span><h1>Find work that fits your skills.</h1><p>Search connected opportunities, track applications and keep your profile ready.</p><div className="searchbar"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Job title, skill or company"/><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="Location"/><button onClick={search}>Search</button></div></section><section className="sectionhead"><div><h2>Recommended opportunities</h2><p className="muted">Live roles from your connected job sources.</p></div><button className="iconbtn" onClick={load}><RefreshCw size={18}/></button></section><div className="grid">{featured.map(j=><JobCard key={j.id} j={j} track={track}/>)}</div></>}
 {tab==='jobs'&&<><section className="pagehead"><h1>Job search</h1><p>Explore current opportunities from connected sources.</p></section><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search jobs"/><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="Location"/><button onClick={search}>Search</button></div><div className="list">{jobs.map(j=><JobCard key={j.id} j={j} track={track}/>)}</div></>}
 {tab==='applications'&&<><section className="pagehead"><h1>Applications</h1><p>Keep every tracked opportunity in one place.</p></section><div className="panel">{apps.length?apps.map(a=><div className="row" key={a.id}><div><b>Job {a.job_id.slice(0,8)}</b><small>{a.status}</small></div><ChevronRight size={18}/></div>):<div className="empty"><Briefcase size={30}/><b>No applications tracked yet</b><span>Track a job from the Jobs tab.</span></div>}</div></>}
 {tab==='profile'&&<><section className="pagehead"><h1>Your profile</h1><p>Preferences power better matching.</p></section><div className="panel form"><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Skills<input value={skills} onChange={e=>setSkills(e.target.value)}/></label><label>Preferred locations<input value={locations} onChange={e=>setLocations(e.target.value)}/></label><label className="check"><input type="checkbox" checked={remote} onChange={e=>setRemote(e.target.checked)}/> Prefer remote roles</label><button onClick={save}>Save & sync profile</button></div></>}
 {tab==='settings'&&<><section className="pagehead"><h1>Settings</h1><p>Connection and release information.</p></section><div className="panel"><div className="row"><div><b>Backend</b><small>{API}</small></div><Wifi size={18}/></div><div className="row"><div><b>App version</b><small>10.5.0 Production Candidate</small></div></div><div className="row"><div><b>Connected features</b><small>Jobs · Profile · Applications · Alerts API</small></div><Target size={18}/></div></div></>}
 </main><nav>{[['home',Home,'Home'],['jobs',Search,'Jobs'],['applications',Bookmark,'Applications'],['profile',UserRound,'Profile'],['settings',Settings,'Settings']].map(([k,I,label])=><button className={tab===k?'active':''} onClick={()=>setTab(k as string)} key={k as string}><I size={20}/><span>{label as string}</span></button>)}</nav>{loading&&<div className="loading"><RefreshCw className="spin" size={18}/> Syncing</div>}</div>
}
function JobCard({j,track}:{j:Job;track:(j:Job)=>void}){return <article className="job"><div className="jobtop"><div className="companyicon">{j.company?.[0]||'J'}</div><div><h3>{j.title}</h3><b>{j.company}</b></div></div><div className="meta"><span><MapPin size={15}/>{j.location||'Location not listed'}</span>{j.remote&&<span>Remote</span>}<span>{j.source}</span>{j.salary&&<span>{j.salary}</span>}</div><div className="actions"><a href={j.canonical_url} target="_blank" rel="noreferrer">Apply <ExternalLink size={15}/></a><button onClick={()=>track(j)}><CheckCircle2 size={15}/> Track</button></div></article>}
createRoot(document.getElementById('root')!).render(<App/>);
